title: "Ixchel's Portfolio"
description: "Portfolio of Ixchel"
 
author:
  name: "Ixchel"
  email: "ixchel@example.com"
  github_username: "ipm"
  linkedin: "Ixchel-peralta"
theme: jekyll-theme-minimal
exclude:
  - "README.md"
  - "LICENSE"

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: "assets" 
    values:
      permalink: /assets/:path/
