title: "Your Name"
description: "Portfolio of Your Name - Developer, Designer, Creator"

author:
  name: "Ixchel"
  email: "ixchel@example.com"
  github_username: "ipm"
  linkedin: "Ixchel-peralta"
  
theme: minima

nav_links:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap 
  
exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
