title: "Ixchel's Portfolio"
description: "Portfolio of Ixchel"
url: "https://ixchel.github.io"
baseurl: ""

author:
  name: "Ixchel"
  email: "ixchel@example.com"
  github_username: "ipm"
  linkedin: "Ixchel-peralta"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
exclude:
  - "README.md"
  - "LICENSE"
