title: "Ixchel's Portfolio"
description: "Portfolio of Ixchel - Developer, Designer, Creator"
url: "https://ixchel.github.io"
baseurl: ""

author:
  name: "Ixchel"
  email: "ixchel@example.com"
  github_username: "ipm"
  linkedin: "Ixchel-peralta"

theme: minima

nav_links:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

