title: "Ixchel's Portfolio"
description: "Portfolio of Ixchel"
url: "https://ixchel.github.io"
baseurl: ""

author:
  name: "Ixchel"
  email: "ixchel@example.com"
  github_username: "ipm"
  linkedin: "Ixchel-peralta"

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

exclude:
  - "README.md"
  - "LICENSE"

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: "assets" 
    values:
      permalink: /assets/:path/
