title: "Ixchel's Portfolio"
description: "Portfolio of Ixchel - Developer, Designer, Creator"
url: "https://ixchel.github.io"
baseurl: ""

author:
  name: "Ixchel"
  email: "ixchel@example.com"
  github_username: "ipm"
  linkedin: "Ixchel-peralta"

theme: minima

header_pages:
  - index.md
  - projects.md
  - about.md
  - contact.md

minima:
  skin: classic  # Change to 'dark', 'auto', etc. based on your preference.
  date_format: "%b %-d, %Y"

show_excerpts: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
