title: "Ixchel's Portfolio"
description: "Portfolio of Ixchel"
theme: jekyll-theme-minimal

exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"

# Markdown and Highlighter Settings
markdown: kramdown
highlighter: rouge
