title: "Ixchel's Portfolio"
description: "Portfolio of Ixchel"
url: "https://ixchel.github.io"
baseurl: ""

author:
  name: "Ixchel"
  email: "ixchel@example.com"
  github_username: "ipm"
  linkedin: "Ixchel-peralta"

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
exclude:
  - "README.md"
  - "LICENSE"
